name: CI Workflow
 
on:
  push:
    branches:
      - main
  pull_request:
     branches:
     - main
 
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Build dockerfile
        run: docker build -t shipit .
     
      - name: Run dockerfile
        run: docker run --rm shipit
